// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqCvJZnY37k9ZEA6u_kDh0OlQ0fHedV08',
    appId: '1:223205643791:web:7a274e8c4aa185a12eb57a',
    messagingSenderId: '223205643791',
    projectId: 'lianxieryi',
    authDomain: 'lianxieryi.firebaseapp.com',
    storageBucket: 'lianxieryi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYONJrIfrlKIvbb7LnOZJGEI9wjY-19sg',
    appId: '1:223205643791:android:33ed5e488635b3ea2eb57a',
    messagingSenderId: '223205643791',
    projectId: 'lianxieryi',
    storageBucket: 'lianxieryi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2vJZsvEZjy6tLxC91DKn51QEku8Mlr3I',
    appId: '1:223205643791:ios:0ac3e0d23d93804a2eb57a',
    messagingSenderId: '223205643791',
    projectId: 'lianxieryi',
    storageBucket: 'lianxieryi.firebasestorage.app',
    iosBundleId: 'com.example.vonotalky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2vJZsvEZjy6tLxC91DKn51QEku8Mlr3I',
    appId: '1:223205643791:ios:0ac3e0d23d93804a2eb57a',
    messagingSenderId: '223205643791',
    projectId: 'lianxieryi',
    storageBucket: 'lianxieryi.firebasestorage.app',
    iosBundleId: 'com.example.vonotalky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqCvJZnY37k9ZEA6u_kDh0OlQ0fHedV08',
    appId: '1:223205643791:web:92e57c48e4e86b7b2eb57a',
    messagingSenderId: '223205643791',
    projectId: 'lianxieryi',
    authDomain: 'lianxieryi.firebaseapp.com',
    storageBucket: 'lianxieryi.firebasestorage.app',
  );
}
